name: Beautiful Jekyll CI
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: '3.1'

      - name: Install Jekyll dependencies
        run: |
          gem install bundler jekyll
          bundle install

      - name: Build Jekyll site
        run: jekyll build

