name: Beautiful Jekyll CI
on: [push, pull_request]
jobs:
  build:
    name: Build Jekyll
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Build site using Jekyll Docker container
        run: |
          docker pull jekyll/builder:3.8
          docker run --rm \
            -v $(pwd):/srv/jekyll \
            -v $(pwd)/_site:/srv/jekyll/_site \
            -w /srv/jekyll \
            jekyll/builder:3.8 bash -c "
              gem update --system &&
              bundle install &&
              jekyll build
            "
